### ISSUE TITLE
find-python in module/python/core/libpython.scm

### ISSUE THREAD

**Issue by byulparan** [koji-kojiro/guile-python#5]
my system: MacOS-10.15.6 / GNU Guile 3.0.4 / Python-3.7.4

currently my system installed python-3.7.4 and has libpython3.7
but `guile-python` can't find my libpython. because it has floating point problem.

 GNU Guile 3.0.4
```scheme
scheme@(guile-user)> (- 3.9 0.1)
$1 = 3.8
scheme@(guile-user)> (- 3.8 0.1)
$2 = 3.6999999999999997
```

so `find-python` can't find libpython3.7

**Comment by koji-kojiro** [comment]
Thank you for the report.
fixed in de7496a433b3d879626725e327244ad70bd4669b
